[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
kadence = "DEZbB6Lzz6nrbeZW9EtA5XNbu1SfAKcgEALfmKLpMECK"

[programs.devnet]
kadence = "DEZbB6Lzz6nrbeZW9EtA5XNbu1SfAKcgEALfmKLpMECK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
