[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault = "AmiknhZoficTbeV33KT2LQheAYKQuJp7pBdquRR4ZkKA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
